### ISSUE TITLE
Deprecation warning on GOV.UK pages

### ISSUE THREAD

**Issue by alextea** [alphagov/static#1053]
A deprecation warning appears in the javascript console when viewing pages on GOV.UK

> Deprecation warning: Custom radio buttons and checkboxes (released in GOV.UK Elements 3.0.0) no longer require this JavaScript.

**Comment by nickcolley** [comment]
Template Consolidation team is currently doing some work into integrating GOV.UK Elements into GOV.UK Publishing which will allow us to remove this. 👍

**Comment by fofr** [comment]
@nickcolley’s argument no longer applies – we aren't continuing to incorporate Elements as we found it’s styles to have affects on unexpected things and there will not be a clean upgrade path to GOV.UK Frontend when it's ready.

**Comment by tijmenb** [comment]
Fixed by https://github.com/alphagov/govuk_frontend_toolkit/pull/454
