### ISSUE TITLE
The warning sign on mobile on this start page is broken

### ISSUE THREAD

**Issue by joelanman** [alphagov/static#1061]
![image](https://cloud.githubusercontent.com/assets/1132904/26453914/4b3ca9ba-415d-11e7-8ab7-9d0575d101aa.png)

https://www.gov.uk/book-driving-test

The bottom is cut off, and I'm not sure the alignment is correct.

**Comment by alextea** [comment]
The issue is that this [block of code](https://github.com/alphagov/static/blob/f44470edc4e4159ea37481985c641034741623ac/app/assets/stylesheets/helpers/_text.scss#L306) is overriding the margin set on the element.
