### ISSUE TITLE
Emergency banner doesn't handle commas in Rake arguments

### ISSUE THREAD

**Issue by fofr** [alphagov/static#1109]
Discovered during the Emergency Publishing Drill:
https://trello.com/c/iniJbqCt/321-emergency-publishing-drill-monday-7-august
https://github.com/alphagov/static/blob/master/lib/tasks/emergency_banner.rake

The link text "Norwegian journalist and statesman, dies at 71" rendered as "Norwegian journalist and statesman".

Rake arguments need to escape commas as commas are used to split arguments:
https://github.com/ruby/rake/issues/21

When typing these fields into Jenkins it's not obvious that commas must be escaped.

**Comment by boffbowsh** [comment]
Can the Jenkins job quote the arguments?

**Comment by fofr** [comment]
We're already quoting arguments:
```
emergency_banner:deploy[\"$CAMPAIGN_CLASS\",\"$HEADING\",\"$SHORT_DESCRIPTION\",\"$LINK\",\"$LINK_TEXT\"]"
```

**Comment by fofr** [comment]
Adding comments to Jenkins fields:
https://github.com/alphagov/govuk-puppet/pull/6242

**Comment by nickcolley** [comment]
Looks to be fixed
