### ISSUE TITLE
Cached components may break after new styles deployed

### ISSUE THREAD

**Issue by fofr** [alphagov/static#1121]
We stumbled on this after #1117 and #1119 and had to implement fixes we later reverted in a follow up deploy like #1120.

If we modify both HTML and styles for a component in a deployment a quirk of caching means that the styling and markup can get out of sync. We saw this on govenrment-frontend.

It happens because:
* an app [caches calls to components](https://github.com/alphagov/slimmer/pull/191), creating a cached version of the template
* when a new static deploy is released we update the styles and the templates
* when the page cache expires, a new page is returned with the updated static styling
* BUT: the component may still be cached, so the new page ends up with new styling and old HTML
* when that cache expires, eventually a new page with new component template and new styles is returned

For a PR like #1119, if we hadn't caught this then for a period of ~15 minutes any users hitting a page that was cached with new styles and old component templates wouldn't have correctly styled titles.

Screenshot of the problem with pagination:
![screen_shot_2017-08-24_at_12 09 03](https://user-images.githubusercontent.com/319055/29715736-76a12bb8-89a0-11e7-8dcf-7d429d7aec3e.png)

**Comment by tijmenb** [comment]
This has been solved by moving all components into the gem.
