### ISSUE TITLE
Active links in government navigation are hard to read

### ISSUE THREAD

**Issue by fofr** [alphagov/static#1167]
The active link colour in the government navigation feels hard to read.

![screen shot 2017-10-12 at 16 36 34](https://user-images.githubusercontent.com/319055/31504929-8f2be6dc-af6b-11e7-8d00-d807ac78a4e0.png)

![screen shot 2017-10-12 at 16 48 16](https://user-images.githubusercontent.com/319055/31505602-3011af36-af6d-11e7-9f67-8981e045e310.png)

Despite _feeling_ hard to read the contrast ratio passes our accessibility tests, with a ratio of 5.8. The blue is significantly lighter than `govuk-blue` (#1d8feb vs #005ea5) presumably to meet contrast ratios.
http://leaverou.github.io/contrast-ratio/#%230b0c0c-on-%231d8feb

![#1d8feb](https://placehold.it/40/1d8feb/000000?text=+) `#1d8feb`
![#005ea5](https://placehold.it/40/005ea5/000000?text=+) `#005ea5`

**Comment by nickcolley** [comment]
Related thread: https://twitter.com/heydonworks/status/897711844303024130

https://ux.shopify.com/in-plain-sight-5639c9afb4c6 (edited)

http://designworkplan.com/design/signage-and-color-contrast.htm

**Comment by andysellick** [comment]
Closing as header on GOV.UK has been rebuilt.
