### ISSUE TITLE
Should we let users press enter to get a new line?

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/static#1205]
I recently tried to use the "Is there anything wrong with this page?" to report an issue. I pressed return / enter to get a new line so I could structure my feedback better. Sadly, this submitted the form instead.

What's really sad, is that even if you realise what's happened, it won't let you submit the form again. A user attempting a new line has to work out that they need to refresh the page.

We may not want to encourage longer submissions, but I feel like we should be more careful about helping prevent accidental submissions which are then hard to correct.

**Comment by nickcolley** [comment]
There are many issues with this part of GOV.UK, and it's something that gets avoided since it's not really owned by anyone.

We should definitely address this.

**Comment by tijmenb** [comment]
The "Is there anything wrong with this page?" feature has moved to a component. We're likely to look into the working of the feedback form next quarter, so I've created a card to track this suggestion: https://trello.com/c/Xp9BB0sc/50-feedback-component-pressing-enter
