### ISSUE TITLE
Feedback form is not accessible

### ISSUE THREAD

**Issue by nickcolley** [alphagov/static#1206]
"Is there anything wrong with this page?" form at the bottom of every page does not indicate if it's open or closed to uses of assistive tech.

This means to them nothing appears which would prevent these users from sending feedback if they did not discover the content below.

We should reimplement this pattern with a pattern similar to https://govuk-elements.herokuapp.com/typography/#typography-hidden-text

I imagine there's more issues similar including https://github.com/alphagov/static/issues/1205 but I've not had time to do a full audit.

**Comment by tijmenb** [comment]
We've replaced this feature with the "Yes/No" feedback component, so this particular issue is solved.
