### ISSUE TITLE
Can't use components in components

### ISSUE THREAD

**Issue by andysellick** [alphagov/static#1234]
Currently building a component for the 'is this page useful?' form to go at the footer of GOV.UK, based on what is already on the [Service Manual](https://www.gov.uk/service-manual). This component includes a button. It would be useful to be able to use the existing [button component](https://govuk-static.herokuapp.com/component-guide/button) for this, but can't, due to the way static/slimmer works together.

Specifically, it's possible to include a component within a component in the browser, but errors like this occur in tests:

Error:
FeedbackTestCase#test_asks_the_user_if_there_is_anything_wrong_with_the_page_without_javascript_enabled:
ActionView::Template::Error: Missing partial govuk_component/_button with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
  * "/var/govuk/static/app/views"
  * "/usr/lib/rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/govuk_publishing_components-2.0.0/app/views"

Reusing components like this would mean components depend upon each other (reducing isolation) but it would also massively help reduce duplicate CSS/JS/etc.

Long term these components may live [in the components gem](https://github.com/alphagov/govuk-rfcs/pull/84) where this problem could be avoided, but issues of duplicate CSS/JS across apps have yet to be addressed.

**Comment by tijmenb** [comment]
This will be possible when all components live in the gem (https://trello.com/c/pU7YINt1).
