### ISSUE TITLE
Get started button icon position on mobile breakpoint

### ISSUE THREAD

**Issue by dashouse** [alphagov/static#1248]
The icon on the get started button is cut off on the mobile breakpoint. 

Although there is a specific `background-position` for this breakpoint, it is is set to 110%.
I would suggest changing to something more like 104% for it to be centred inside the right hand padding.

![getstarted-button](https://user-images.githubusercontent.com/23356842/34575068-5a919370-f171-11e7-9819-9c6a028b0bfc.jpg)

**Comment by nickcolley** [comment]
This is the old legacy CSS that hasn't been replaced with the new component variation where fixed this issue.

The markup lives in alphagov/frontend (where we should add the component code) and the CSS is in  this repo (which we should remove when it's all gone)

**Comment by steventux** [comment]
@dashouse @nickcolley see https://github.com/alphagov/frontend/pull/1402 this PR has been merged. Will be verifying this works on integration this afternoon.

**Comment by steventux** [comment]
https://www-origin.integration.publishing.service.gov.uk/vehicle-tax
vs.
https://www.gov.uk/vehicle-tax

The button styling is different when using the component, it's simpler and may well solve this issue.

**Comment by tijmenb** [comment]
This seems to have been fixed by using the magic of components 🎉
