### ISSUE TITLE
Global bar focus state inconsistent

### ISSUE THREAD

**Issue by injms** [alphagov/static#1945]
Both the links in the global bar look strange when focused. 

The 'Register to vote' link takes up the entire width of the parent element:

<img width="700" alt="" src="https://user-images.githubusercontent.com/1732331/69431063-d9aef500-0d2e-11ea-9d10-f45cc92623e2.png">

A quick fix for this could be to remove `display: block` from the link, and set the following `span` to be `display: block`.

and the 'Hide message' link has too much space at the bottom:
<img width="154" alt="" src="https://user-images.githubusercontent.com/1732331/69431070-dd427c00-0d2e-11ea-885d-6b44a845f4c4.png">

This can be fixed by changing the element's style from `bottom: 0` to `top: 0`.

**Comment by andysellick** [comment]
I've been meaning to report this for about a week now. Just to add that the fix isn't quite that simple, the `bottom: 0` is used for mobile, so worth checking when implementing.

**Comment by injms** [comment]
Ah yes, I thought the fix wouldn't be this easy - I should've said 'possibly be fixed' rather than 'can be fixed' 😃

**Comment by danacotoran** [comment]
Closing this issue as the global bar no longer looks like this (feel free to reopen if I'm wrong!)
