### ISSUE TITLE
"Search on GOV.UK" label text is cut off on mobile (portrait) view.

### ISSUE THREAD

**Issue by issyl0** [alphagov/static#2301]
Hello friends!

On my OnePlus 7 Pro (Google Chrome browser), I just noticed that the "Search on GOV.UK" search box label text (changed in #2290 as part of an accessibility review) is _slightly_ cut off in portrait view.

Thanks! 💖

Here's a screenshot, to help visualise.

![Screenshot_20201017-202747](https://user-images.githubusercontent.com/355033/96352164-1dce8500-10b9-11eb-9aba-28c61e214007.jpg)

**Comment by issyl0** [comment]
Oooh, I just realised that #2293 might fix this as it resets the label text to just "Search". 🤔

**Comment by injms** [comment]
A fix for this has been merged in, and will be deployed as soon as possible. Thank you @issyl0! 🙌
