### ISSUE TITLE
Test user's Do Not Track preference before including Google Analytics

### ISSUE THREAD

**Issue by alexmuller** [alphagov/static#393]
[Jeremy wrote an interesting post about testing `navigator.doNotTrack` client-side](http://adactio.com/journal/6767/) before including the Google Analytics snippet.

That seems very sensible (I don't know much about the spec) and it seems like something that we of all people should be doing.

I would be interested in your thoughts.

**Comment by nickcolley** [comment]
Medium deals with this in an interesting way.

https://medium.com/policy/how-we-handle-do-not-track-requests-on-medium-f2b4b4fb7c5e#.njnuspz0k

![screen shot 2016-10-31 at 15 36 33](https://cloud.githubusercontent.com/assets/2445413/19860558/0ce34c38-9f81-11e6-80fd-2bf0030564d6.png)

**Comment by injms** [comment]
Unfortunately I'm closing this issue as the [DNT working group is closed][1], the [status as reported on MDN is 'Obsolete'][3], and [Apple has removed support][2].


[1]: https://github.com/w3c/dnt/blob/f6d39ec81728cb240cf8f55d695886b18e5d6dc9/README.md
[2]: https://gizmodo.com/apple-is-removing-do-not-track-from-safari-1832400768
[3]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack#specifications
