### ISSUE TITLE
Active items in guides are outdented vs other parts

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/static#676]
Active items in gov.uk guides are outdented vs the other parts. This as the effect of making the parts jump around if you click between the parts.

![screen shot 2015-11-19 at 13 43 25](https://cloud.githubusercontent.com/assets/2204224/11273774/1ae0a26a-8ecd-11e5-89f6-b1c87aad7936.png)

**Comment by nickcolley** [comment]
Not sure why this was done: https://github.com/alphagov/static/commit/11302c0274a45ba193c0148b4c41cdd092ee9736

**Comment by edwardhorsford** [comment]
Can we fix it?

**Comment by nickcolley** [comment]
@edwardhorsford yes, I'm going to do it :)

**Comment by nickcolley** [comment]
Thanks for raising, once we deploy static you should see this fixed in production 😄
