### ISSUE TITLE
Inconsistency in font-size of context within page titles

### ISSUE THREAD

**Issue by fofr** [alphagov/static#703]
In the image below, the left is a rendering from frontend, the middle is a component in the government-frontend (with the `long` section removed), the third is from elements, and the fourth from the component guide.

cc @dsingleton @gemmaleigh 
## In context

![screen shot 2016-01-08 at 16 52 00](https://cloud.githubusercontent.com/assets/319055/12203689/39b9531c-b628-11e5-8279-6b75fd6eeaea.png)
## By themselves

![screen shot 2016-01-08 at 16 50 30](https://cloud.githubusercontent.com/assets/319055/12203653/043bf35c-b628-11e5-8147-c8d25471f8ad.png)

**Comment by dsingleton** [comment]
This is an issue in component guide, where app styles are overriding components, which needs sorting out (see https://github.com/alphagov/govuk-component-guide/pull/16)

Could you re-open this on Component Guide?

**Comment by fofr** [comment]
Part of this is a component guide issue, that covers the 4th screen, but not the 2nd.

**Comment by dsingleton** [comment]
Didn't spot that :+1: given they're so similar we can _probably_ tweak it on static. 

The only issue would be if anything if depending on the total header height for alignment elsewhere, which is hard to test, as it could be on any FE app consuming the `wrapper` layout. This seems pretty low risk though.

**Comment by tijmenb** [comment]
If I understand it correctly, I think this issue is solved by now (it's 2 years old)? Please reopen if not.
