### ISSUE TITLE
Undefined Method error with ruby buildpack

### ISSUE THREAD

**Issue by djsd123** [alphagov/static#822]
While deploying to paas I get the following error as Garden attempts to use the ruby_buildpack v1.6.19 to compile Static:

`sh: 1: Syntax error: EOF in backquote substitution`
`!     undefined method`[]' for nil:NilClass`
./Gemfile:45:in ruby_requirement': undefined method []' for nil:NilClass (NoMethodError)

Logged with paas team

**Comment by boffbowsh** [comment]
This is a bug in CF's ruby buildpack, it works fine with Heroku's.

For some reason, CF's buildpack isn't defining the `ENV` constant. Perhaps it's sandboxed somehow?

**Comment by boffbowsh** [comment]
Example deployed on Heroku: https://shrouded-stream-94588.herokuapp.com/static/crests/org_crest_27px_x2-3eb6258ba699c8ae2c3cf370e8a4422f37bdae95ae084a99115841a8bf0543a7.png

**Comment by djsd123** [comment]
I was aware of that @boffbowsh. I just need to keep track of it.

**Comment by boffbowsh** [comment]
Ah, fair enough :)

**Comment by djsd123** [comment]
Thanks

**Comment by nickcolley** [comment]
@djsd123 can we close this out?

**Comment by nickcolley** [comment]
Please reopen if this is still an issue 😄
