### ISSUE TITLE
Implement keyboard events for links with a role of button

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/static#825]
govuk_frontend_toolkit 4.15.0 will include [a shim](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/anchor-buttons.js) for fixing keyboard events on links with a role of `button`. In the frontend meeting it was decided that we’d implement this in static initially to test, and then decide whether to migrate it over to govuk_template. @cfq also requested that this usage was recorded in analytics too so that we can see how many people this affects.

**Comment by gemmaleigh** [comment]
For further context, here's the [discussion on GOV.UK elements](https://github.com/alphagov/govuk_elements/pull/272), which led to the creation of the shim to allow anchors with `role="button"` to be 'clicked' via the space key. (thanks to @paulmsmith).

**Comment by gemmaleigh** [comment]
The govuk_frontend_toolkit has now been updated to 4.15.0, so this work can go ahead.

**Comment by gemmaleigh** [comment]
Here's how it's used in govuk_elements:

```
  // Use GOV.UK shim-links-with-button-role.js to trigger a link styled to look like a button,
  // with role="button" when the space key is pressed.
  GOVUK.shimLinksWithButtonRole.init()
```

**Comment by nickcolley** [comment]
Just realised that this should be 'keyDown' not 'keyUp' since the page currently scrolls and then follows the link..
