### ISSUE TITLE
Changes to template header search will need minor change to static

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/static#848]
Changes in [this GOV.UK Template PR](https://github.com/alphagov/govuk_template/pull/259) will mean a minor fix is needed in static.

That PR moves the focus outline inside of the input, but this leaves a white border to the right of the search input. This is caused by the search in put and button being separated and their container having a white background.

Rather oddly this white border is 1px in Chrome, but 2px in Safari.

Don't know what the fix would be, as the white background is needed to make the placeholder work.

The button also has a 1px left border of #222 ideally this would be changed to our standard black.

Screenshot of the issue:
![screen shot 2016-11-04 at 14 29 48](https://cloud.githubusercontent.com/assets/2204224/20015266/b3b0af0e-a2b2-11e6-9198-c903558454be.png)

**Comment by 36degrees** [comment]
The white background is required because the input is transparent when it is not focussed and it does not contain any text, displaying the label which is otherwise obscured by the input.

**Comment by edwardhorsford** [comment]
Thanks @36degrees, I've amended the issue to remove my suggested fix.

**Comment by fofr** [comment]
I've bumped template locally to 0.20.0 and see this in Chrome, without any changes:
![screen shot 2017-05-05 at 12 00 48](https://cloud.githubusercontent.com/assets/319055/25743088/83a45b32-318a-11e7-88ec-b7762d20358f.png)

**Comment by andysellick** [comment]
@fofr @edwardhorsford is this issue resolved? Can this issue be closed?

**Comment by edwardhorsford** [comment]
I *don't* think it is, but my memory is fuzzy on this.

The current page has a `outline-offset: -2px;` - whereas it _should_ be `3px`.

If you change `outline-offset` to `3px`, the issue still exists - there's a white line. I suspect we didn't go with 3px because it looked better without whilst this bug existed.

The search button itself still has the incorrect black left border.

**Comment by andysellick** [comment]
I'm having a crack at this. Latest Chrome and FF seem happy but Safari still a problem.
