### ISSUE TITLE
Pagination rendering poorly due to poorly scoped CSS conflict

### ISSUE THREAD

**Issue by nickcolley** [alphagov/static#851]
Issue found while visiting the Scottish Government's Device Lab

Example page: https://www.gov.uk/benefit-cap/benefits-included-in-the-cap

![image](https://cloud.githubusercontent.com/assets/2445413/20500540/b02a2666-b02d-11e6-8293-f17ac6512a2c.png)

Potentially can be solved short term by moving the pagination styles below the content-block styles in source order, or moving the pagination in the application out of the scope of content-block.

Ideally the position of a component's markup should not influence how it is rendered, however since we have generated content (govspeak) we might not be able to avoid the cascade entirely unless we change the rendering of govspeak to include strict classes to bind to...

**Comment by robinwhittleton** [comment]
Moving it outside the content block fixes it but also changes the font size. I expect we actually want the smaller font? We’d also need to move the print icon out as that’s within the content block and after the pagination.

![Example of pagination offset within the content block](https://cloud.githubusercontent.com/assets/7414/21603936/6622e1b6-d198-11e6-9e0e-4fca1e94d880.gif)

**Comment by fofr** [comment]
government-frontend rendering:
![screen shot 2017-05-10 at 14 41 57](https://cloud.githubusercontent.com/assets/319055/25901470/d64bc052-358e-11e7-9897-e9ebb10fac50.png)

**Comment by nickcolley** [comment]
💯  🚀
