### ISSUE TITLE
Option selects aren’t set up correctly when open on page load

### ISSUE THREAD

**Issue by quis** [alphagov/static#860]
If an option select is set to be open (expanded) when the page loads then:
- the button which controls it’s opening/closing has its `aria-expanded` attribute set to `false`, even though it is open
- the code which [sets the height of the options container](https://github.com/alphagov/static/pull/556) doesn’t get executed, so users may not realise that the options are scrollable

***

Both issues can be seen here (on [the Competition and Markets Authority cases page](https://www.gov.uk/cma-cases)):

![opt-select](https://cloud.githubusercontent.com/assets/355079/20883045/ef687298-badb-11e6-992e-704d46a0877d.gif)

**Comment by nickcolley** [comment]
If you toggle the input it'll set both the clipping and the aria attribute correctly.

Looks like the initialising is not sharing the same code as the open/close.

**Comment by quis** [comment]
@nickcolley Yeah that’s what I thought. Is this the kind of thing that would get into your team’s backlog or would I be better off looking at it myself?
