### ISSUE TITLE
Remove jQuery UI

### ISSUE THREAD

**Issue by fofr** [alphagov/static#868]
We have some uses of jQuery UI sprinkled throughout static:

A copy of jQuery UI in the `vendor/assets` directory:
https://github.com/alphagov/static/tree/master/vendor/assets/stylesheets/admin
It was added 4 years ago. Is anything using it?

A reference in  the youtube video link enhancer: https://github.com/alphagov/static/blob/9e8795b262c948a65b798029864cbe04f193262a/app/assets/javascripts/govuk-component/govspeak-enhance-youtube-video-links.js#L1

It appears to be used in the jQuery tabs plugin for keyboard input:
https://github.com/alphagov/static/blob/9e8795b262c948a65b798029864cbe04f193262a/app/assets/javascripts/jquery.tabs.js

We attempt to precompile a version in production that doesn't exist:
https://github.com/alphagov/static/blob/9e8795b262c948a65b798029864cbe04f193262a/config/environments/production.rb#L43
See https://github.com/alphagov/static/commit/239318f8ad050c49ad53fbefba37a74aba8e46fb

**Comment by robinwhittleton** [comment]
There‘s also a bunch of `ui-*` images: https://github.com/alphagov/static/tree/master/app/assets/images

**Comment by alex-ju** [comment]
jQuery tabs was removed in #1612. I'll look into removing it from `govspeak-enhance-youtube-video` and make sure it's not being used elsewhere.

**Comment by kr8n3r** [comment]
this will be removed in https://github.com/alphagov/govuk_publishing_components/pull/908

**Comment by kr8n3r** [comment]
I believe that with the new video enhancement shipped, there is no more jquery-ui

**Comment by alex-ju** [comment]
@kr8n3r: yes, I think now it's safe to assume so.
