### ISSUE TITLE
Add development CSS for a11y and security issues

### ISSUE THREAD

**Issue by nickcolley** [alphagov/static#872]
I was thinking we could add a development only asset that flags up obvious accessibility issues and also a security issue.

Similar to https://ffoodd.github.io/a11y.css/

For example with https://github.com/alphagov/static/issues/871 we could flag this up too.

This would mean if people use markup in a way we know will cause issues we could flag it to them when they're in development and testing their changes.

We could also run automated tests for this but I thought this might be a low-fi way that is easy to implement.

**Comment by tijmenb** [comment]
Cleaning up issues - I think this is largely implemented by the A11n tests in the component system. Feel free to reopen!
