### ISSUE TITLE
Guide print styles have small text in tables and low contrast text

### ISSUE THREAD

**Issue by nickcolley** [alphagov/static#887]
![screencapture-gov-uk-vehicle-tax-rate-tables-print-1485518689150](https://cloud.githubusercontent.com/assets/2445413/22370341/e2746192-e488-11e6-87a0-0394ceb69bfc.png)

Low contrast text at the bottom

**Comment by andysellick** [comment]
Example URL: https://www.gov.uk/vehicle-tax-rate-tables

These pages have been updated since this issue was logged and now look quite different and the issues have been addressed.
