### ISSUE TITLE
Rendering of vcards

### ISSUE THREAD

**Issue by andrewgarner** [alphagov/static#909]
The rendering of vcards has changed Government Frontend from the previous behaviour in Whitehall. The following illustrate the new visual treatment applied to News Articles now that they are rendered by Government Frontend.

I discussed this with @fofr who suggested raising an issue to investigate further.

### Example URLs

- https://www.gov.uk/government/news/new-streamlined-jobcentre-plus-network-with-more-support-for-jobseekers
- https://www.gov.uk/government/news/setting-standards-for-new-gcses-in-2017
- https://www.gov.uk/government/news/lord-mcnallys-response-to-the-youth-justice-reform-announcement

### Example screenshots

![1080x3000_phantomjs_production](https://cloud.githubusercontent.com/assets/2715/23302071/087a572c-fa85-11e6-889e-db7c30f75752.png)
![1080x3000_phantomjs_local](https://cloud.githubusercontent.com/assets/2715/23302072/087f86fc-fa85-11e6-8efd-c2f603826e6a.png)
![600x4000_phantomjs_production](https://cloud.githubusercontent.com/assets/2715/23302074/087fb654-fa85-11e6-8176-5a7a2be6ee6f.png)
![600x4000_phantomjs_local](https://cloud.githubusercontent.com/assets/2715/23302073/087f95d4-fa85-11e6-84c1-dc2dfeb05fbb.png)
![320x5000_phantomjs_production](https://cloud.githubusercontent.com/assets/2715/23302076/08832e24-fa85-11e6-8ccd-df35326c6928.png)
![320x5000_phantomjs_local](https://cloud.githubusercontent.com/assets/2715/23302075/0882a0d0-fa85-11e6-8212-319f3daf1448.png)

**Comment by nickcolley** [comment]
I'm struggling to see what I should be focusing on in this issue, can you break it down more and show before and after, with detail why it's an issue etc.

**Comment by tijmenb** [comment]
Closing this as it's a bit unclear what the problem/solution is here. Please reopen if there's more information available.
